#!/usr/bin/env python3
import argparse
import math
import subprocess
from pathlib import Path


def read_pgm(path: Path):
    with path.open('rb') as f:
        magic = f.readline().strip()
        if magic != b'P5':
            raise ValueError(f'{path}: unsupported magic {magic!r}')

        def read_token():
            while True:
                line = f.readline()
                if not line:
                    raise ValueError(f'{path}: unexpected EOF in header')
                line = line.strip()
                if not line or line.startswith(b'#'):
                    continue
                return line

        size = read_token().split()
        if len(size) != 2:
            raise ValueError(f'{path}: invalid size line {size!r}')
        width, height = int(size[0]), int(size[1])
        maxval = int(read_token())
        if maxval != 255:
            raise ValueError(f'{path}: unsupported maxval {maxval}')

        data = f.read(width * height)
        if len(data) != width * height:
            raise ValueError(f'{path}: payload truncated ({len(data)} != {width * height})')
        return width, height, data


def compute_metrics(out_pgm: Path, ref_pgm: Path):
    w1, h1, d1 = read_pgm(out_pgm)
    w2, h2, d2 = read_pgm(ref_pgm)

    w = min(w1, w2)
    h = min(h1, h2)
    if w <= 0 or h <= 0:
        raise ValueError('invalid overlap size')

    sse = 0.0
    sae = 0.0
    max_abs = 0
    for y in range(h):
        o1 = y * w1
        o2 = y * w2
        for x in range(w):
            diff = d1[o1 + x] - d2[o2 + x]
            ad = abs(diff)
            sse += diff * diff
            sae += ad
            if ad > max_abs:
                max_abs = ad

    mse = sse / (w * h)
    psnr = float('inf') if mse == 0 else 10.0 * math.log10((255.0 * 255.0) / mse)
    mae = sae / (w * h)
    return {
        'output_size': (w1, h1),
        'ref_size': (w2, h2),
        'overlap': (w, h),
        'mse': mse,
        'psnr': psnr,
        'mae': mae,
        'max_abs': max_abs,
    }


def run(cmd):
    print('$', ' '.join(str(x) for x in cmd))
    subprocess.run(cmd, check=True)


def main():
    parser = argparse.ArgumentParser(description='Generate a first-frame reference and compare it against the current VVC decoder output.')
    parser.add_argument('--decoder', default='./build/vvc_decoder', help='decoder executable path')
    parser.add_argument('--bitstream', default='demo.h266', help='input VVC bitstream')
    parser.add_argument('--output', default='output_first_frame.pgm', help='decoder output pgm')
    parser.add_argument('--ref', default='ref_000.pgm', help='reference pgm generated by ffmpeg')
    parser.add_argument('--skip-decode', action='store_true', help='skip running decoder')
    args = parser.parse_args()

    decoder = Path(args.decoder)
    bitstream = Path(args.bitstream)
    out_pgm = Path(args.output)
    ref_pgm = Path(args.ref)

    if not args.skip_decode:
        run([str(decoder), str(bitstream)])

    if not out_pgm.exists():
        raise FileNotFoundError(f'missing decoder output: {out_pgm}')

    run([
        'ffmpeg', '-hide_banner', '-loglevel', 'error', '-y',
        '-i', str(bitstream),
        '-frames:v', '1', '-vf', 'format=gray',
        str(ref_pgm),
    ])

    metrics = compute_metrics(out_pgm, ref_pgm)
    print('output_size:', metrics['output_size'])
    print('ref_size   :', metrics['ref_size'])
    print('overlap    :', metrics['overlap'])
    print('MSE        :', f"{metrics['mse']:.6f}")
    print('PSNR       :', 'inf' if math.isinf(metrics['psnr']) else f"{metrics['psnr']:.6f} dB")
    print('MAE        :', f"{metrics['mae']:.6f}")
    print('MaxAbsDiff :', metrics['max_abs'])


if __name__ == '__main__':
    main()
